run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - typecheck
    - unused
    - gosec
    - gofmt
    - goimports
    - gocritic
    - revive
    - misspell
    - unparam
    - nakedret
    - prealloc
    - exportloopref

linters-settings:
  gosec:
    excludes:
      - G204 # Subprocess launched with variable
  gocritic:
    enabled-checks:
      - nestingReduce
      - unnamedResult
      - ruleguard
      - truncateCmp

issues:
  exclude-rules:
    # Disable gosec for test files
    - path: _test\.go
      linters:
        - gosec
    # Disable some linters for embedded files
    - path: embedded_lua/
      linters:
        - gocritic
        - revive
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true